# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20161128_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysummary',
            name='cable',
            field=models.DecimalField(decimal_places=2, default=64.15, max_digits=9),
        ),
        migrations.AddField(
            model_name='monthlysummary',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlysummary',
            name='insurance',
            field=models.DecimalField(decimal_places=2, default=59.51, max_digits=9),
        ),
        migrations.AddField(
            model_name='monthlysummary',
            name='laserincome',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='monthlysummary',
            name='members_cornerstone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlysummary',
            name='members_full',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlysummary',
            name='members_fullwarden',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlysummary',
            name='members_student',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlysummary',
            name='members_studentwarden',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlysummary',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='monthlysummary',
            name='otherexpense',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='monthlysummary',
            name='otherincome',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='monthlysummary',
            name='pnc_beginning',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='monthlysummary',
            name='pnc_deductions',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='monthlysummary',
            name='pnc_deposits',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='monthlysummary',
            name='pnc_ending',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='monthlysummary',
            name='pp_beginning',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='monthlysummary',
            name='pp_credits',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='monthlysummary',
            name='pp_ending',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='monthlysummary',
            name='pp_fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='monthlysummary',
            name='pp_transfers',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='monthlysummary',
            name='rent',
            field=models.DecimalField(decimal_places=2, default=1150.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='monthlysummary',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=0),
        ),
        migrations.AlterField(
            model_name='monthlysummary',
            name='year',
            field=models.IntegerField(choices=[(2009, b'2009'), (2010, b'2010'), (2011, b'2011'), (2012, b'2012'), (2013, b'2013'), (2014, b'2014'), (2015, b'2015'), (2016, b'2016')], default=0),
        ),
    ]
