# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20161128_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysummary',
            name='pp_payments',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='monthlysummary',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=11),
        ),
        migrations.AlterField(
            model_name='monthlysummary',
            name='year',
            field=models.IntegerField(choices=[(2009, b'2009'), (2010, b'2010'), (2011, b'2011'), (2012, b'2012'), (2013, b'2013'), (2014, b'2014'), (2015, b'2015'), (2016, b'2016')], default=2016),
        ),
    ]
