# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 07:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20180228_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlydata',
            name='combinedbeginning',
        ),
    ]
