# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_remove_monthlydata_combinedbeginning'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlydata',
            name='pnc_outreach_beginning',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='monthlydata',
            name='pnc_outreach_deductions',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='monthlydata',
            name='pnc_outreach_deposits',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='monthlydata',
            name='pnc_outreach_ending',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
