# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_auto_20180228_0443'),
    ]

    operations = [
            migrations.RenameField('MonthlyData', 'pnc_beginning', 'pnc_main_beginning'),
            migrations.RenameField('MonthlyData', 'pnc_deposits', 'pnc_main_deposits'),
            migrations.RenameField('MonthlyData', 'pnc_deductions', 'pnc_main_deductions'),
            migrations.RenameField('MonthlyData', 'pnc_ending', 'pnc_main_ending'),
    ]
