# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-21 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import finance.models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_auto_20180228_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlydata',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=finance.models.DefaultMonth),
        ),
        migrations.AlterField(
            model_name='monthlydata',
            name='year',
            field=models.IntegerField(choices=[(2009, b'2009'), (2010, b'2010'), (2011, b'2011'), (2012, b'2012'), (2013, b'2013'), (2014, b'2014'), (2015, b'2015'), (2016, b'2016'), (2017, b'2017'), (2018, b'2018'), (2019, b'2019')], default=finance.models.DefaultYear),
        ),
    ]
